### ISSUE TITLE
Location to the Implementation of Feature Consistency Loss

### ISSUE THREAD

**Issue by vhvkhoa** [gengshan-y/viser-release#8]
Hello,

I would like to ask about the implementation of feature consistency loss in your source code.
I was looking through the nnutils/mesh_net.py but could only find match loss and cycle (reprojection) loss, and `imatch loss` (maybe inverse match loss), which seems not reported in the paper.

Would you please help me locate the implementation of feature consistency loss ?

Thank you in advance.

**Comment by gengshan-y** [comment]
Hi,

Feature consistency loss is not used in the code release since we found it can be removed without loss of reconstruction accuracy. Feature matching loss + re-projection loss was good enough.

But if you are interested in the implementation of it, check this
https://github.com/gengshan-y/viser-release/blob/502ac589b7be0a5a0307625cca167b27e19c6914/nnutils/mesh_net.py#L99-L117

https://github.com/gengshan-y/viser-release/blob/502ac589b7be0a5a0307625cca167b27e19c6914/nnutils/mesh_net.py#L784-L800

**Comment by vhvkhoa** [comment]
Hello,

Thank you very much for your clarification. I would like to follow up by another question related to reprojection loss.
I notice that at Line 849 in the code part below:

https://github.com/gengshan-y/viser-release/blob/eac3a8e0599e56781e6bf69a0428e62d7907eccc/nnutils/mesh_net.py#L846-L869

`csm_points` is detached from the whole network. Therefore, I am wondering which parts of your model is optimized by re-projection loss ?

**Comment by gengshan-y** [comment]
The articulation parameters and camera parameters (e.g., G, W in eq 1.) are updated by the reprojection loss. feature embedding is only updated by the 3d matching loss (eq 9).
